### ISSUE TITLE
blade mem-load cache mode does not work

### ISSUE THREAD

**Issue by sunny-xiao** [chaosblade-io/chaosblade#926]
## Issue Description

Type: *bug report*
when i use a command '**blade c mem load --mode cahce --mem-percent 90**' to burn my cache , **it does not work, the cache size remained same**(i use top to observe),the error log is as follows:
1、the log shows no burnmem_tmpfs dir, so i create one:
<img width="1154" alt="image" src="https://github.com/chaosblade-io/chaosblade/assets/33513943/6458c254-ab93-498d-affc-f6a9ae67429f">
<img width="1151" alt="image" src="https://github.com/chaosblade-io/chaosblade/assets/33513943/1e52f472-c76c-499a-85a3-d5c6dafad82a">
2、after creating, it shows another error, you can see count is 0 which is obviously wrong
<img width="1169" alt="image" src="https://github.com/chaosblade-io/chaosblade/assets/33513943/3d8646a6-a600-4cf3-a4db-a3f3953ced75">
the enviroment i used is **oracle linux server 7.6**, and the arch is **x86_64**
the blade version is 1.7.2

**Comment by hengyoush** [comment]
it seems the tmpfs is not correctly mount to burnmem_tmpfs, i have committed a pr to fix this issue.

**Comment by sunny-xiao** [comment]
has the PR merged yet?

**Comment by ash-man** [comment]
I'm testing 'mem load mode cache' on the latest version 1.7.4 and it seems it was not resolved until then ...

**Comment by ash-man** [comment]
Yeah, I can confirm that in 1.7.4: 
1. directory burnmem_tmpfs doesn't exist 
2. even if manually created tempfs is not mounted to burnmem_tmpfs
3. experiment failed 

It seems that it hasn't been resolved yet.

**Comment by CodeHcy** [comment]
I also encountered this problem. The version is 1.7.4. When injecting memory load into k8s node, it fails. The chaos-os process crashes when it is created, and an error message is given when it is destroyed that the process is not found.

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/bug` | Status: **Confirmed** | Severity: **Medium**

`blade c mem load --mode cache --mem-percent 90` does not work. Two issues reported:
1. `burnmem_tmpfs` directory doesn't exist
2. After creating it manually, the write count is 0

**Root Cause (identified by @hengyoush):** The `tmpfs` is not correctly mounted to `burnmem_tmpfs`. A fix PR was submitted but appears not to have been merged or released.

**Status:** As of v1.7.4 (confirmed by @ash-man in 2024-09), this issue remains **unresolved**.

**Impact:** The `cache` mode for memory experiments is completely non-functional, limiting users to `ram` mode only.

**Affected Component:** `chaosblade-exec-os` memory load cache mode implementation

**Recommendation:** The pending PR fix should be reviewed and merged. If the original PR is stale, the fix should be re-implemented. This is a long-standing bug that affects a core experiment type.

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
